# Etapa 1: Construir a aplicação
# Usar uma imagem oficial do Node.js como a base para construir a aplicação
FROM node:16 AS build 

# Configurar o diretório de trabalho no contêiner
WORKDIR /app

# Copiar o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar todos os arquivos do projeto para o diretório de trabalho
COPY . .

# Definir a variável de ambiente para a URL da API
ENV QUARKUS_APP_API_URL=http://meu-backend:8081

# Construir a aplicação para produção
RUN npm run build

# Etapa 2: Servir a aplicação
# Usar uma imagem oficial do Nginx para servir a aplicação
FROM nginx:alpine

# Criar um diretório de trabalho no Nginx
WORKDIR /usr/share/nginx/html

# Copiar os arquivos de construção do diretório de construção para o diretório do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expor a porta 80 para o tráfego HTTP
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]